---
- name: add dns servers
  template: 
    src=~/myStack/ansible/roles/common/templates/tail.j2
    dest=/etc/resolvconf/resolv.conf.d/tail
    owner=root
    group=root
    mode=0644
  notify: restart resolvconf
